# ABOUT PROJECT
Hi my name is Akisha Bhujel, I am an aspiring data analyst. I'm skilled in python, sql and this is my first project on Power BI, about Multi-Channel Sales & Distribution Analytics Dashboard. this project include cleaning raw dataset and use powerbi to visualize trends and solve business questions. Right now, the raw dataset has many missing values, inconsistent formats, and invalid business values. It is a real-world messy retail sales dataset with data quality issues.

The objective of this project is to visualize sales performance to generate meaningful insights to help generate revenue and identify key performance indicators. The tools used for this project are Python and Power BI. This dataset contains sales records of a product-based company selling electronic products across multiple different regions. The dataset is collected from an open-source Kaggle dataset. You can download the zip file for this dataset from the given link: [kaggle dataset link](https://www.kaggle.com/datasets/somesomeall/electronic-retails-dataset)

In [1]:
# IMPORT THE LIBRARY AND DATASET INTO NOTEBOOK FOR UNDERSTANDING AND CLEANING.

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv('SalesData.csv')
df

,Date,Product,Category,Quantity,Price,Discount_%,Total_Sales,Region,Sales_Channel,Payment_Method,Customer_Type,Customer_Rating,Delivery_Days
0,"Wednesday, January 1, 2020",Office Chair,Furniture,2,375000,5.0,300.0,Bago,NaN,NaN,NaN,5.0,2.0
1,1/2/2020,Desk,Furniture,21,750000 MMK,0.0,6300.0,Mandalay,Agent,Mobile Pay,VIP,1.0,NaN
2,1/3/2020,Mouse,Accessories,14,62500 MMK,NaN,350.0,Yangon,NaN,NaN,VIP,4.0,7.0
3,1/4/2020,Mouse,Accessories,3,62500 MMK,0.0,75.0,Yangon,NaN,Credit Card,Retail,4.0,-1.0
4,1/5/2020,Laptop,Electronics,0,2000000.0 MMK,0.0,NaN,Mandalay,Agent,Mobile Pay,Retail,2.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295,7/19/2023,Headphones,Accessories,17,125000 MMK,10.0,850.0,Naypyidaw,In-Store,Cash,Wholesale,3.0,7.0
1296,"Thursday, July 20, 2023",Office Chair,Furniture,15,375000 MMK,10.0,2250.0,Yangon,Agent,Credit Card,Wholesale,5.0,1.0
1297,7/21/2023,Keyboard,Accessories,13,100000 MMK,15.0,520.0,Mandalay,In-Store,Cash,Wholesale,4.0,1.0
1298,7/22/2023,Headphones,Accessories,7,125000 MMK,0.0,350.0,Mandalay,NaN,Credit Card,Wholesale,2.0,1.0
1299,7/23/2023,Mouse,Accessories,19,62500 MMK,NaN,475.0,Mandalay,Online,Credit Card,NaN,5.0,3.0

In [3]:
# LOOKING AT THE FIRST FIVE ROW AND LAST FIVE ROW WE CAN UNDERSTAND THE DATASET HAS ALOT OF INCONSISTENT FORMAT AND MISSING VALUES.
# LETS CHECK THE SHAPE OF DATAFRAME WITH TOTAL COLUMN AND ROWS.

In [4]:
df.shape

(1300, 13)

In [5]:
# THE DATAFRAME HAS TOTAL 13 COLUMN WITH MORE THEN 1000 ROWS, NEXT WE NEED TO CHECK MISSING VALUES AND IF THE VALUES ARE IN CORRECT DATATYPE.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             1300 non-null   object
 1   Product          1300 non-null   object
 2   Category         1300 non-null   object
 3   Quantity         1300 non-null   int64
 4   Price            1300 non-null   object
 5   Discount_%       1039 non-null   float64
 6   Total_Sales      1174 non-null   float64
 7   Region           1045 non-null   object
 8   Sales_Channel    971 non-null    object
 9   Payment_Method   979 non-null    object
 10  Customer_Type    991 non-null    object
 11  Customer_Rating  1072 non-null   float64
 12  Delivery_Days    1110 non-null   float64
dtypes: float64(4), int64(1), object(8)
memory usage: 132.2+ KB

In [7]:
# FROM THE GIVEN INFO PRICE IS NOT IN ACCURATE DATATYPE AND 8 COLUMNS HAS MISSING VALUES IN IT.

In [8]:
df['Price'] = df['Price'].astype(str)
df['Price'] = df['Price'].str.replace(',', '', regex=False)
df['Price'] = df['Price'].str.replace('MMK', '', regex=False)
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df

,Date,Product,Category,Quantity,Price,Discount_%,Total_Sales,Region,Sales_Channel,Payment_Method,Customer_Type,Customer_Rating,Delivery_Days
0,"Wednesday, January 1, 2020",Office Chair,Furniture,2,375000.0,5.0,300.0,Bago,NaN,NaN,NaN,5.0,2.0
1,1/2/2020,Desk,Furniture,21,750000.0,0.0,6300.0,Mandalay,Agent,Mobile Pay,VIP,1.0,NaN
2,1/3/2020,Mouse,Accessories,14,62500.0,NaN,350.0,Yangon,NaN,NaN,VIP,4.0,7.0
3,1/4/2020,Mouse,Accessories,3,62500.0,0.0,75.0,Yangon,NaN,Credit Card,Retail,4.0,-1.0
4,1/5/2020,Laptop,Electronics,0,2000000.0,0.0,NaN,Mandalay,Agent,Mobile Pay,Retail,2.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295,7/19/2023,Headphones,Accessories,17,125000.0,10.0,850.0,Naypyidaw,In-Store,Cash,Wholesale,3.0,7.0
1296,"Thursday, July 20, 2023",Office Chair,Furniture,15,375000.0,10.0,2250.0,Yangon,Agent,Credit Card,Wholesale,5.0,1.0
1297,7/21/2023,Keyboard,Accessories,13,100000.0,15.0,520.0,Mandalay,In-Store,Cash,Wholesale,4.0,1.0
1298,7/22/2023,Headphones,Accessories,7,125000.0,0.0,350.0,Mandalay,NaN,Credit Card,Wholesale,2.0,1.0
1299,7/23/2023,Mouse,Accessories,19,62500.0,NaN,475.0,Mandalay,Online,Credit Card,NaN,5.0,3.0

In [9]:
# AFTER CHANGING THE DATATYPE NOW ITS TIME FO DROP AND FILL EMPTY ROWS

In [10]:
df.isnull().sum()

Date                 0
Product              0
Category             0
Quantity             0
Price                9
Discount_%         261
Total_Sales        126
Region             255
Sales_Channel      329
Payment_Method     321
Customer_Type      309
Customer_Rating    228
Delivery_Days      190
dtype: int64

In [11]:
# DEALING WITH EMPTY ROW SINCE PRICE ONLY HAD 9 MISSING VALUES I DECIDE TO DROP IT RATHER THEN FILL VALUE AND BRING OUTLIERS. 
# FOR CUSTOMER RSTING AND DELIVERY DAY I USED REPLACED WITH MEDIAN VALUE.
# IF THE DISCOUNT ROW IS EMPTY THEN ITS NO DISCOUNT HENCE ZERO PERCENT DISOUNT.

In [12]:
df = df.dropna(subset=['Price'])
df['Customer_Rating'] = df['Customer_Rating'].fillna(df['Customer_Rating'].median())
df['Delivery_Days'] = df['Delivery_Days'].fillna(df['Delivery_Days'].median())
df['Discount_%'] = df['Discount_%'].fillna(0)
df['Sales_Channel'] = df['Sales_Channel'].fillna('Unknown')
df['Region'] = df['Region'].fillna('Unknown')
df

,Date,Product,Category,Quantity,Price,Discount_%,Total_Sales,Region,Sales_Channel,Payment_Method,Customer_Type,Customer_Rating,Delivery_Days
0,"Wednesday, January 1, 2020",Office Chair,Furniture,2,375000.0,5.0,300.0,Bago,Unknown,NaN,NaN,5.0,2.0
1,1/2/2020,Desk,Furniture,21,750000.0,0.0,6300.0,Mandalay,Agent,Mobile Pay,VIP,1.0,2.0
2,1/3/2020,Mouse,Accessories,14,62500.0,0.0,350.0,Yangon,Unknown,NaN,VIP,4.0,7.0
3,1/4/2020,Mouse,Accessories,3,62500.0,0.0,75.0,Yangon,Unknown,Credit Card,Retail,4.0,-1.0
4,1/5/2020,Laptop,Electronics,0,2000000.0,0.0,NaN,Mandalay,Agent,Mobile Pay,Retail,2.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295,7/19/2023,Headphones,Accessories,17,125000.0,10.0,850.0,Naypyidaw,In-Store,Cash,Wholesale,3.0,7.0
1296,"Thursday, July 20, 2023",Office Chair,Furniture,15,375000.0,10.0,2250.0,Yangon,Agent,Credit Card,Wholesale,5.0,1.0
1297,7/21/2023,Keyboard,Accessories,13,100000.0,15.0,520.0,Mandalay,In-Store,Cash,Wholesale,4.0,1.0
1298,7/22/2023,Headphones,Accessories,7,125000.0,0.0,350.0,Mandalay,Unknown,Credit Card,Wholesale,2.0,1.0
1299,7/23/2023,Mouse,Accessories,19,62500.0,0.0,475.0,Mandalay,Online,Credit Card,NaN,5.0,3.0

In [13]:
# NOW GENERATE NEW FEATURE FROM ALREADY EXISTING COLUMN TO CREATE MORE INSIGHTFUL MESSAGE.

In [14]:
df['Discount'] = df['Quantity'] * df['Price'] * (df['Discount_%'] / 100)
df['Amount'] = df['Quantity'] * df['Price'] * (1 - df['Discount_%'] / 100)
df

,Date,Product,Category,Quantity,Price,Discount_%,Total_Sales,Region,Sales_Channel,Payment_Method,Customer_Type,Customer_Rating,Delivery_Days,Discount,Amount
0,"Wednesday, January 1, 2020",Office Chair,Furniture,2,375000.0,5.0,300.0,Bago,Unknown,NaN,NaN,5.0,2.0,37500.0,712500.0
1,1/2/2020,Desk,Furniture,21,750000.0,0.0,6300.0,Mandalay,Agent,Mobile Pay,VIP,1.0,2.0,0.0,15750000.0
2,1/3/2020,Mouse,Accessories,14,62500.0,0.0,350.0,Yangon,Unknown,NaN,VIP,4.0,7.0,0.0,875000.0
3,1/4/2020,Mouse,Accessories,3,62500.0,0.0,75.0,Yangon,Unknown,Credit Card,Retail,4.0,-1.0,0.0,187500.0
4,1/5/2020,Laptop,Electronics,0,2000000.0,0.0,NaN,Mandalay,Agent,Mobile Pay,Retail,2.0,5.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295,7/19/2023,Headphones,Accessories,17,125000.0,10.0,850.0,Naypyidaw,In-Store,Cash,Wholesale,3.0,7.0,212500.0,1912500.0
1296,"Thursday, July 20, 2023",Office Chair,Furniture,15,375000.0,10.0,2250.0,Yangon,Agent,Credit Card,Wholesale,5.0,1.0,562500.0,5062500.0
1297,7/21/2023,Keyboard,Accessories,13,100000.0,15.0,520.0,Mandalay,In-Store,Cash,Wholesale,4.0,1.0,195000.0,1105000.0
1298,7/22/2023,Headphones,Accessories,7,125000.0,0.0,350.0,Mandalay,Unknown,Credit Card,Wholesale,2.0,1.0,0.0,875000.0
1299,7/23/2023,Mouse,Accessories,19,62500.0,0.0,475.0,Mandalay,Online,Credit Card,NaN,5.0,3.0,0.0,1187500.0

In [15]:
# CREATING NEW COLUMN NOW ITS TIME FOR DROPPING ANY VALUELESS ATTRIBUTE

In [16]:
df = df.drop(columns=[
    'Date',
    'Discount_%',
    'Payment_Method',
    'Customer_Type',
    'Delivery_Days',
    'Price',
    'Quantity',
    'Product',
    'Customer_Rating'
])
df = df.dropna(subset=['Total_Sales'])
df

         Category  Total_Sales     Region Sales_Channel  Discount      Amount
0       Furniture        300.0       Bago       Unknown   37500.0    712500.0
1       Furniture       6300.0   Mandalay         Agent       0.0  15750000.0
2     Accessories        350.0     Yangon       Unknown       0.0    875000.0
3     Accessories         75.0     Yangon       Unknown       0.0    187500.0
5     Accessories        240.0     Yangon      In-Store   90000.0    510000.0
...           ...          ...        ...           ...       ...         ...
1295  Accessories        850.0  Naypyidaw      In-Store  212500.0   1912500.0
1296    Furniture       2250.0     Yangon         Agent  562500.0   5062500.0
1297  Accessories        520.0   Mandalay      In-Store  195000.0   1105000.0
1298  Accessories        350.0   Mandalay       Unknown       0.0    875000.0
1299  Accessories        475.0   Mandalay        Online       0.0   1187500.0

[1166 rows x 6 columns]

In [17]:
# NOW THAT I HAVE DROP ANY USELESS COLUMN AND EMPTY ROWS LETS CHECK DATATYPE AND NULL VALUES AGAIN

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1166 entries, 0 to 1299
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Category       1166 non-null   object
 1   Total_Sales    1166 non-null   float64
 2   Region         1166 non-null   object
 3   Sales_Channel  1166 non-null   object
 4   Discount       1166 non-null   float64
 5   Amount         1166 non-null   float64
dtypes: float64(3), object(3)
memory usage: 63.8+ KB

In [19]:
# AFTER DATA CLEANING IM LEFT WITH 6 COLUMN AND 1166 ROWS FOR ANALYZATION 
# NEXT STEP IS TO DOWNLOAD CSV AND WORK ON POWER BI <3

In [20]:
df.to_csv('Distribution Analytics.csv', index=False)

In [21]:
# AFTER CLEANING DATASET I LOADED, TRANSFORM, VISUALIZE AND MADE A POWERBI DASHBOARD

from IPython.display import Video
Video("https://res.cloudinary.com/dvz4rrtdz/video/upload/v1777140797/VIDEO-2026-04-25-22-44-04_et2ptz.mp4")

![gif](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZGhkZWN0NnI2bnh0OGc0cm8xcTVtd3BqaDVndmYyOW5sdnJueThybCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Wa6hhrJdOkU8TSZ6E4/giphy.gif)